###################
## HYPRLAND CONF ##
###################

# exec-once = systemctl --user import-environment XDG_CONFIG_HOME

exec-once = waybar
exec-once = hyprpaper
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"  
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 24

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$TERMINAL = kitty
$EDITOR = kitty nvim
$EXPLORER = nautilus
$BROWSER = firefox

###################
##### SOURCES #####
###################

$mainMod = SUPER # Sets "Windows" key as main modifier

source = ./keybindings.conf
source = ./windowsrules.conf
source = ./nvidia.conf
source = ./monitors.conf
source = ./variables.conf
source = ./userprefs.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct


