splash = false

wallpaper {
    monitor = DP-1
    # path = ~/Media/Wallpapers/Custom/55192173787_6bfa3237c5_4k.jpg
    # path = /home/kryoseu/Media/scv-3-skeletonversion-1+copy.jpg
    # path = ~/Media/Wallpapers/Custom/55193054741_e5d4cb1e24_4k.jpg
    path = ~/Media/Wallpapers/Graphite Mono/japan_lake.jpg
    fit_mode = cover
}
