###############
#### NVDIA ####
###############

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

# https://wiki.hyprland.org/Nvidia/#regarding-environment-variables
# If you encounter crashes in Firefox, remove this line
env = GBM_BACKEND,nvidia-drm
