##################
### USER PREFS ###
##################

# ==========================================
# Startup Applications
# ==========================================

exec-once = NetworkManager
exec-once = protonvpn-app

# ==========================================
# Extra Key Binds
# ==========================================

bind = $mainMod Control, 1, exec, kitty nvim ~/.config 
bind = $mainMod Control, 2, exec, kitty nvim ~/.config/hypr/userprefs.conf
bind = $mainMod Control, 3, exec, kitty nvim ~/.zshrc

# Suggested NiflVeil bindings
# Minimize current window and updates the interface
bind = $mainMod, M, exec, /usr/local/bin/niflveil minimize
# Opens the EWW interface              
bind = $mainMod, I, exec, /usr/local/bin/niflveil restore
# Restore the last minimized window
bind = SUPER, U, exec, /usr/local/bin/niflveil restore-last
# Restore all minimized windows 
bind = $mainMod SHIFT, U, exec, /usr/local/bin/niflveil restore-all
# PS: If you are using the EWW window, add the following to the end
# of the bindings: "&& eww reload --config /etc/xdg/eww/widgets/niflveil"

