# See https://wiki.hyprland.org/Configuring/Window-Rules/

# ==========================================
# Window Rules
# ==========================================

# ------------------------
# Float and Center Windows
# ------------------------

# ## Speedcrunch
windowrule = match:class org.speedcrunch.speedcrunch, float on
windowrule = match:class org.speedcrunch.speedcrunch, size 500 500
windowrule = match:class org.speedcrunch.speedcrunch, center on

# ## Kitty
# windowrule = match:class kitty, match:title kitty, float on
# windowrule = match:class kitty, size 900 650
# windowrule = match:class kitty, match:title kitty, center on

# ## KeePassXC
windowrule = match:class org.keepassxc.KeePassXC, float on
windowrule = match:class org.keepassxc.KeePassXC, size 900 650
windowrule = match:class org.keepassxc.KeePassXC, center on

# ## Dolphin
# windowrule = match:class org.kde.dolphin, float on
# windowrule = match:class org.kde.dolphin, size 900 650
# windowrule = match:class org.kde.dolphin, center on

# ## Nautilus
# windowrule = match:class org.gnome.Nautilus, float on
# windowrule = match:class org.gnome.Nautilus, center on

# ## ProtonVPN
windowrule = match:class protonvpn-app, float on
windowrule = match:class protonvpn-app, size 800 600
windowrule = match:class protonvpn-app, center on

# ## Network Manager
windowrule = match:class nm-connection-editor, float on
windowrule = match:class nm-connection-editor, center on

# ## Pavucontrol
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = center on, match:class org.pulseaudio.pavucontrol
